// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestratorOpportunityStatus } from "./OrchestratorOpportunityStatus";
import type { OrchestratorRisk } from "./OrchestratorRisk";

export type OrchestratorOpportunity = { id: string, workspaceKey: string, title: string, rationale: string, status: OrchestratorOpportunityStatus, priority: number, impactScore: number, confidence: number, estimatedCost: number, risk: OrchestratorRisk, dedupeKey: string, createdByRunId: string | null, completedByRunId: string | null, createdAt: number, updatedAt: number, };
