// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestratorLedgerOutcome } from "./OrchestratorLedgerOutcome";

export type OrchestratorWorkLedgerEntry = { id: string, workspaceKey: string, taskTitle: string, outcome: OrchestratorLedgerOutcome, touchedAreas: Array<string>, blockers: Array<string>, dedupeKey: string, runId: string | null, createdAt: number, updatedAt: number, };
