// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrchestratorSchedule = { id: string, workspaceKey: string, enabled: boolean, cadenceSeconds: number, nextRunAt: number, lastRunAt: number | null, roleOverride: string | null, modelOverride: string | null, maxSpawnedAgents: number, maxRunSeconds: number, baseTokenBudget: number, currentTokenBudget: number, minTokenBudget: number, maxTokenBudget: number, consecutiveLowValueRuns: number, consecutiveLoopDetections: number, };
