// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { OrchestratorRunPhase } from "./OrchestratorRunPhase";
import type { OrchestratorRunStatus } from "./OrchestratorRunStatus";
import type { OrchestratorVerificationOutcome } from "./OrchestratorVerificationOutcome";

export type OrchestratorRun = { id: string, scheduleId: string | null, workspaceKey: string, phase: OrchestratorRunPhase, status: OrchestratorRunStatus, scoutTokens: number, executionTokens: number, subagentTokens: number, budgetUsed: number, spawnedAgentCount: number, impactScore: number | null, summary: string | null, decisions: JsonValue, loopFlags: JsonValue, verifierOutcome: OrchestratorVerificationOutcome | null, goalUpdates: JsonValue, startedAt: number, completedAt: number | null, };
