// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestratorVerificationOutcome } from "./OrchestratorVerificationOutcome";

export type OrchestratorVerificationCompletedNotification = { runId: string, outcome: OrchestratorVerificationOutcome, summary: string | null, };
