// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceGoalSource } from "./WorkspaceGoalSource";
import type { WorkspaceGoalStatus } from "./WorkspaceGoalStatus";

export type WorkspaceGoal = { id: string, workspaceKey: string, objective: string, source: WorkspaceGoalSource, status: WorkspaceGoalStatus, priority: number, createdAt: number, updatedAt: number, completedAt: number | null, };
