// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteClientCapabilities = {
/**
 * The client can render file diffs in a reviewable form.
 */
rendersDiffs: boolean,
/**
 * The client can answer approval requests from the user.
 */
answersApprovals: boolean,
/**
 * The client can submit file attachments or other binary user input.
 */
supportsFileAttachments: boolean,
/**
 * The client can receive command output notifications.
 */
receivesCommandOutput: boolean, };
